# Generated by Django 4.2.3 on 2023-09-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0002_alter_customuser_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='netflixapp.profile'),
        ),
    ]
